### ISSUE TITLE
【简化】mihomo-stop.vbs 双击运行停止 mihomo

### ISSUE THREAD

**Issue by aubur20240314** [ewigl/mihomo#2]
```vbs
Dim WShell
Set WShell = CreateObject("WScript.Shell")
WShell.Run "powershell -Command ""Get-Process -Name mihomo | Stop-Process""", 0
Set WShell = Nothing
```

**Comment by ewigl** [comment]
这个脚本在你的电脑上可以正常运行吗？

在我的电脑上，tun模式默认是管理员权限运行的，这个脚本没有管理员权限会被拒绝访问无法停止mihomo。

另外就是可执行程序名我用的是默认的`mihomo-windows-amd64`，不是`mihomo`。

**Comment by aubur20240314** [comment]
@ewigl 我暂时没用 tun 模式，可以试试这个

**Comment by ewigl** [comment]
> @ewigl 我暂时没用 tun 模式，可以试试这个
> 
> ```vbnet
> Dim objShell
> Set objShell = CreateObject("Shell.Application")
> objShell.ShellExecute "powershell.exe", "-Command ""Get-Process -Name mihomo-windows-amd64 | Stop-Process""", "", "runas", 1
> Set objShell = Nothing
> ```

这个可以，感谢建议，你可以提交PR。
